config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comment, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comment.create(params[:comment].permit(:name, :body))
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comment.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @posts = Post.all.order('created_at Desc')
    end

    def new
        @post = Post.new
    end

    def create
     @post = Post.new(post_params)
     
     if @post.save
        redirect_to @post
     else
        render 'new'
     end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(params[:post].permit(:title, :body))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end

    private

    def post_params
        params.require(:post).permit(:title,:body)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><em><%= comment.name %></em></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_title"><%= time_ago_in_words(comment.created_at) %>Ago</p>
    </div>
    <% if user_signed_in? %>
        <p> <%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure?'} %></p>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comment.build]) do |f|%>

    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :body %> <br>
        <%= f.text_area :body %>
    </p>
    <br>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Raleway:400,700" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to "Tumblr", root_path %></li>
        <li> <%= link_to "Posts", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if !user_signed_in? %>
          <li class="sign_in"><%= link_to "User Login", new_user_session_path %></li>
        <% end %>
        </ul>
      
    </div>

  
    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p> My Site </p>
        <% else %>
          <%= link_to "Back to Post Feed", root_path %>
        <% end %>
        <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to "Make Post", new_post_path %></button>
            <button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </button>
          </div>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert" ) %>
      <% end %>
      <%= yield %>
    </div>
   
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
    <div id="profile_image">
        <%= image_tag "profile.jpeg" %>
    </div>

    <div id="content">
        <h1>It's Mr. Stick Figure</h1>
        <p>Lorem Ipsum es simplemente texto de relleno de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto de relleno estándar de la industria desde la década de 1500, cuando un impresor desconocido tomó una galera de tipos y la mezcló para hacer un libro de muestras tipográfico. Ha sobrevivido no solo a cinco siglos, sino también al salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contienen pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker que incluye versiones de Lorem Ipsum.</p>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
            <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Fix Post</h1>

    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="body"><%= truncate(post.body, length:100) %></p>
        <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1>Make Something</h1>

    <%= form_for :post, url: posts_path do |f| %>
        <% if @post.errors.any? %>
            <div id="errors">
                <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving </h2>
                <ul>
                    <% @post.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <p>
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </p>

        <p>
            <%= f.label :body %><br>
            <%= f.text_area :body %>
        </p>

        <p>
            <%= f.submit %>
        </p>

    <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%= @post.title%>
    </h1>

    <p class="date">
        submitted <%= time_ago_in_words(@post.created_at) %> ago |
        <% if user_signed_in? %>
            <%= link_to 'Edit', edit_post_path(@post) %> |
            <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
        <% end %>
    </p>

    <p class="body">
        <%= @post.body %>
    </p>
    <div id="comments">
        <h2><%= @post.comment.count %> Comments</h2>
        <%= render @post.comment %>
        <h3> Join Discussion:</h3>
        <%= render "comments/form" %>
    </div>
</div>